version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: catalogo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MiguelAngel19!
      MYSQL_DATABASE: CatalogoProductos
      MYSQL_USER: admin
      MYSQL_PASSWORD: MiguelAngel19!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: ./webProductos.Api
    container_name: catalogo-api
    restart: always
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=server=db;user=admin;password=MiguelAngel19!;database=CatalogoProductos
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
