version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: catalogo-db
    environment:
      MYSQL_ROOT_PASSWORD: MiguelAngel19!
      MYSQL_DATABASE: CatalogoProductos
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: ./Catalogo.Api
    container_name: catalogo-api
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "server=db;user=root;password=MiguelAngel19!;database=CatalogoProductos"
      Jwt__Key: "UnaContrase√±aSecretaYMuyLargaAqui_12345"
      Jwt__Issuer: "CatalogoApi"
      Jwt__Audience: "CatalogoClient"
    ports:
      - "5079:5079"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
